# Generated by Django 3.0.5 on 2020-04-14 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LiveCodeMVC', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='productelectronics',
            name='category_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='LiveCodeMVC.CategoryId'),
        ),
        migrations.AddField(
            model_name='productmobil',
            name='category_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='LiveCodeMVC.CategoryId'),
        ),
        migrations.AddField(
            model_name='productmotor',
            name='category_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='LiveCodeMVC.CategoryId'),
        ),
    ]
